version: '3.1'

services:

  db:
    image: mysql
    container_name: ass-mysql
    platform: linux/amd64
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: mysql-password
    networks:
      - default

      
  assessment:
    container_name: assessment
    build:
      context: .
      dockerfile: Dockerfile
      args: 
        - REACT_APP_API=http://localhost:8081/students
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
      - 8081:8081
    environment:
      - CHOKIDAR_USEPOLLING=true
    
    networks:
      - default


